name: Website

on:
  push:
    branches: [ "main" ]
    paths:
      - "website/**"
      - ".github/**/website.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "website/**"
      - ".github/**/website.yml"

defaults:
  run:
    working-directory: ./website

jobs:
  build:
    name: Build Svelte
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./website/package-lock.json
    - run: npm ci
    - run: tsc
    - run: npm run build
