name: Website

on:
  push:
    branches: [ "main" ]
    paths:
      - "website/**"
      - ".github/**/website.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "website/**"
      - ".github/**/website.yml"

defaults:
  run:
    working-directory: ./website

jobs:
  build-website:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: ./website/package-lock.json
    - run: npm ci
    - run: tsc
    - run: npm run build
