
name: Website CI

on:
  push:
    paths:
      - "website/**"
      - ".github/**/website.yml"
  pull_request:
    paths:
      - "website/**"
      - ".github/**/website.yml"

defaults:
  run:
    working-directory: website

jobs:
  build-website:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: tsc
    - run: npm run build
    - run: npm test --if-present
